baseURL = "https://example.org/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Kohei TOKURA"
theme = "gokarna"
enableRobotsTXT = true

[params]
  customHeadHTML = """
  <meta name="google-site-verification" content="0jqth7ivsygihGUe8TVuYTYNdKySSzHVWYgDEJbEYeE" />
<style>
main a {
  color: #0066cc !important;
}

main a:hover {
  color: #004999 !important;
  text-decoration: underline !important;
}

.myname {
  text-decoration: underline !important;
  text-underline-offset: 0.14em;
  text-decoration-thickness: 1.2px;
}
</style>
"""
  description = "M2 student in theoretical physics"
  footer = "Kohei TOKURA"
  socialIcons = [
    {name = "email", url = "mailto:u349020e@ecs.osaka-u.ac.jp"}
  ]

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "経歴"
    url = "/career/"
    weight = 2

  [[menu.main]]
    name = "出版"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    name = "発表"
    url = "/talks/"
    weight = 4

  [[menu.main]]
    name = "リンク"
    url = "/links/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
